# Generated by Django 5.2.2 on 2025-07-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('claims_type', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50)),
                ('npi', models.CharField(max_length=50)),
                ('administrator', models.CharField(default='Patrick McCullough', max_length=255)),
                ('telephone', models.CharField(default='(410) 850-8500', max_length=50)),
                ('telefax', models.CharField(default='(410) 850-8655', max_length=50)),
                ('email', models.EmailField(default='planoffice@mmpplans.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='inquiry.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='inquiry.patient')),
            ],
        ),
    ]
