# Generated by Django 5.2.2 on 2025-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='patients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
